Telnet python 3
mushorg/telnetsrvlib pull request #1
Opened 2018-07-11 21:26 UTC by xandfury

[![Build Status](https://travis-ci.org/xandfury/telnetsrvlib.svg?branch=master)](https://travis-ci.org/xandfury/telnetsrvlib) [![Coverage Status](https://coveralls.io/repos/github/xandfury/telnetsrvlib/badge.svg?branch=master)](https://coveralls.io/github/xandfury/telnetsrvlib?branch=master) [![Codacy Badge](https://api.codacy.com/project/badge/Grade/045d2e7fc59747089fe81736ba515738)](https://www.codacy.com/app/xandfury/telnetsrvlib?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=xandfury/telnetsrvlib&amp;utm_campaign=Badge_Grade)

Initial work on telnet lib.

2018-07-12 02:11 UTC, glaslos requested changes

2018-07-12 02:11 UTC, glaslos commented on .travis.yml
> +- '3.5'
what about 3.6?

2018-07-12 02:11 UTC, glaslos commented on telnetsrv/green.py
> +import gevent
we probably want to replace gevent with asyncio

2018-07-12 02:11 UTC, glaslos commented on tox.ini
> +envlist = py35
3.6?

2018-07-12 02:11 UTC, glaslos commented on tox.ini
> +    py35: python3.5
3.6?

2018-07-12 07:11 UTC, xandfury commented on telnetsrv/green.py
> +import gevent
Hey Lukas. Actually Daniel and I thought of using fork for Conpot's telnet server. So the choice of py35 and gevent are derived from there. I have added py36 support though.
It only makes sense to have multiple handlers if we plan to use this fork in multiple projects. 

cc: @creolis What do you think?

2018-07-12 07:16 UTC, xandfury commented
@glaslos @creolis On a side note, please refrain from squashing commits. I think one of these days someone might do a git bisect to look for potential errors.

2018-07-13 08:36 UTC, glaslos commented on telnetsrv/green.py
> +import gevent
@xandfury Sorry, my bad, stick to gevent for now

2018-07-13 08:36 UTC, glaslos commented
LGTM

2018-07-13 08:37 UTC, glaslos approved these changes

2018-07-16 13:06 UTC, merged